### ISSUE TITLE
Error: Error Domain=com.pixelglow.zipzap Code=0 "The operation couldn’t be completed. (com.pixelglow.zipzap error 0.)" UserInfo=0x171461d80 {NSUnderlyingError=0x1700564a0 "The operation couldn’t be completed. (Cocoa error 256.)"}

### ISSUE THREAD

**Issue by benkofk** [pixelglow/ZipZap#109] opened 2015-08-11 08:23 UTC
Hi there,

I've found an issue with the reading of archived files. I've an archive of 30 zips, all about 100mb each.  It gets to the 9th file, and then can't seem to archive any of the file paths, then becomes able again, then not able again all in a loop (i'll show more below). I've tested it by deleting the first 9 zips, and then the second 9 become fine.

Anyway, here's my code if you're interested and the output:

    for(PlaySectionHeader *section in _sectionList){
        for(PlaySectionChild *child in section.children){
            
            NSString* zipfile = [[_documentsPath stringByAppendingPathComponent:section.sectionName] stringByAppendingPathComponent:child.fileName]; 
            
            NSError *error;
            
            ZZArchive* archive = [ZZArchive archiveWithURL:[NSURL fileURLWithPath:zipfile]error:&error];
            
            NSLog(@"**********************************");
            
            if(error) {
                NSLog(@"Error: %@", error);
            }
            
            BOOL fileExists = [[NSFileManager defaultManager] fileExistsAtPath:zipfile];
            
            if(fileExists) {
                NSLog(@"File exists");
            }else{
                NSLog(@"File doesn't exist");
            }
            
            NSData* fileInfoInJSON;
            
            // Iterate through the archive looking for the json file
            for(ZZArchiveEntry *entry in archive.entries){
                NSLog(@"%@", entry.fileName);
                if ([[entry.fileName pathExtension] isEqualToString:@"json"])
                {
                    fileInfoInJSON = [entry newDataWithError:nil];
                }
            }
            
            if(!fileInfoInJSON){
                NSLog(@"Crashed on %@", child.fileName);
                continue;
            }else{
                NSLog(@"Working %@", child.fileName);
            }
            
            NSLog(@"**********************************");
            
            NSDictionary *JSON = [NSJSONSerialization JSONObjectWithData: fileInfoInJSON
                                                                 options:
                                  NSJSONReadingMutableContainers error: nil];
            
            
            
            PmdMetaData *metadata = [[PmdMetaData alloc]init];
          
            // extract info
            metadata.fileName = child.fileName;
            metadata.elrName = [JSON objectForKey:@"elr"];
            metadata.elrFrom = [JSON objectForKey:@"elrfrom"];
            metadata.elrTo = [JSON objectForKey:@"elrto"];
            metadata.lineName = [JSON objectForKey:@"line"];
            
                
            child.jsonData = metadata;
            
            
        }
    }

Output:

 09:14:59.282 [8549:4810886] **********************************
 09:14:59.283 [8549:4810886] File exists
 09:14:59.283 [8549:4810886] Route0/Route0.pmd
 09:14:59.283 [8549:4810886] Route0/Route0.xml
 09:14:59.283 [8549:4810886] Route0/Route0.zip
 09:14:59.284 [8549:4810886] Route1/Route1.pmd
 09:14:59.284 [8549:4810886] Route1/Route1.xml
 09:14:59.284 [8549:4810886] Route1/Route1.zip
 09:14:59.284 [8549:4810886] Route2/Route2.pmd
 09:14:59.285 [8549:4810886] Route2/Route2.xml
 09:14:59.286 [8549:4810886] Route3/Route3.pmd
 09:14:59.286 [8549:4810886] Route3/Route3.xml
 09:14:59.286 [8549:4810886] routeInfo.json
 09:14:59.287 [8549:4810886] RouteMedia.zip
 09:14:59.287 [8549:4810886] Working Demodata.zip
 09:14:59.287 [8549:4810886] **********************************
 09:14:59.291 [8549:4810886] **********************************
 09:14:59.291 [8549:4810886] File exists
 09:14:59.291 [8549:4810886] routeInfo.json
 09:14:59.292 [8549:4810886] Route0/Route0.xml
 09:14:59.292 [8549:4810886] Route0/Route0.pmd
 09:14:59.292 [8549:4810886] Working RDG1_UpMain_18.00_to_17.00_17Feb2015.zip
 09:14:59.293 [8549:4810886] **********************************
 09:14:59.296 [8549:4810886] **********************************
 09:14:59.296 [8549:4810886] File exists
 09:14:59.297 [8549:4810886] routeInfo.json
 09:14:59.297 [8549:4810886] Route0/Route0.xml
 09:14:59.298 [8549:4810886] Route0/Route0.pmd
 09:14:59.298 [8549:4810886] Working RDG1_UpMain_19.00_to_18.00_17Feb2015.zip
 09:14:59.298 [8549:4810886] **********************************
 09:14:59.301 [8549:4810886] **********************************
 09:14:59.301 [8549:4810886] File exists
 09:14:59.301 [8549:4810886] routeInfo.json
 09:14:59.302 [8549:4810886] Route0/Route0.xml
 09:14:59.302 [8549:4810886] Route0/Route0.pmd
 09:14:59.302 [8549:4810886] Working RDG1_UpMain_2.00_to_1.00_17Feb2015.zip
 09:14:59.302 [8549:4810886] **********************************
 09:14:59.305 [8549:4810886] **********************************
 09:14:59.306 [8549:4810886] File exists
 09:14:59.306 [8549:4810886] routeInfo.json
 09:14:59.306 [8549:4810886] Route0/Route0.xml
 09:14:59.307 [8549:4810886] Route0/Route0.pmd
 09:14:59.307 [8549:4810886] Working RDG1_UpMain_20.00_to_19.00_17Feb2015.zip
 09:14:59.307 [8549:4810886] **********************************
 09:14:59.310 [8549:4810886] **********************************
 09:14:59.310 [8549:4810886] File exists
 09:14:59.310 [8549:4810886] routeInfo.json
 09:14:59.311 [8549:4810886] Route0/Route0.xml
 09:14:59.311 [8549:4810886] Route0/Route0.pmd
 09:14:59.311 [8549:4810886] Working RDG1_UpMain_21.00_to_20.00_17Feb2015.zip
 09:14:59.311 [8549:4810886] **********************************
 09:14:59.314 [8549:4810886] **********************************
 09:14:59.314 [8549:4810886] File exists
 09:14:59.315 [8549:4810886] routeInfo.json
 09:14:59.315 [8549:4810886] Route0/Route0.xml
 09:14:59.316 [8549:4810886] Route0/Route0.pmd
 09:14:59.316 [8549:4810886] Working RDG1_UpMain_22.00_to_21.00_17Feb2015.zip
 09:14:59.316 [8549:4810886] **********************************
 09:14:59.318 [8549:4810886] **********************************
 09:14:59.319 [8549:4810886] File exists
 09:14:59.319 [8549:4810886] routeInfo.json
 09:14:59.320 [8549:4810886] Route0/Route0.xml
 09:14:59.320 [8549:4810886] Route0/Route0.pmd
 09:14:59.320 [8549:4810886] Working RDG1_UpMain_23.00_to_22.00_17Feb2015.zip
 09:14:59.320 [8549:4810886] **********************************
 09:14:59.323 [8549:4810886] **********************************
 09:14:59.323 [8549:4810886] File exists
 09:14:59.323 [8549:4810886] routeInfo.json
 09:14:59.324 [8549:4810886] Route0/Route0.xml
 09:14:59.324 [8549:4810886] Route0/Route0.pmd
 09:14:59.325 [8549:4810886] Working RDG1_UpMain_24.00_to_23.00_17Feb2015.zip
 09:14:59.325 [8549:4810886] **********************************
 09:14:59.327 [8549:4810886] **********************************
 09:14:59.328 [8549:4810886] Error: Error Domain=com.pixelglow.zipzap Code=0 "The operation couldn’t be completed. (com.pixelglow.zipzap error 0.)" UserInfo=0x170a760c0 {NSUnderlyingError=0x17004c7b0 "The operation couldn’t be completed. (Cocoa error 256.)"}
 09:14:59.329 [8549:4810886] File exists
 09:14:59.329 [8549:4810886] Crashed on RDG1_UpMain_25.00_to_24.00_17Feb2015.zip
 09:14:59.330 [8549:4810886] **********************************
 09:14:59.331 [8549:4810886] Error: Error Domain=com.pixelglow.zipzap Code=0 "The operation couldn’t be completed. (com.pixelglow.zipzap error 0.)" UserInfo=0x170a76240 {NSUnderlyingError=0x17004c690 "The operation couldn’t be completed. (Cocoa error 256.)"}
 09:14:59.331 [8549:4810886] File exists
 09:14:59.331 [8549:4810886] Crashed on RDG1_UpMain_26.00_to_25.00_17Feb2015.zip
 09:14:59.333 [8549:4810886] **********************************
 09:14:59.334 [8549:4810886] Error: Error Domain=com.pixelglow.zipzap Code=0 "The operation couldn’t be completed. (com.pixelglow.zipzap error 0.)" UserInfo=0x170a76140 {NSUnderlyingError=0x17004cd50 "The operation couldn’t be completed. (Cocoa error 256.)"}
 09:14:59.334 [8549:4810886] File exists
 09:14:59.334 [8549:4810886] Crashed on RDG1_UpMain_27.00_to_26.00_17Feb2015.zip
 09:14:59.337 [8549:4810886] **********************************
 09:14:59.337 [8549:4810886] File exists
 09:14:59.337 [8549:4810886] routeInfo.json
 09:14:59.338 [8549:4810886] Route0/Route0.xml
 09:14:59.338 [8549:4810886] Route0/Route0.pmd
 09:14:59.339 [8549:4810886] Working RDG1_UpMain_28.00_to_27.00_17Feb2015.zip
 09:14:59.339 [8549:4810886] **********************************
 09:14:59.341 [8549:4810886] **********************************
 09:14:59.341 [8549:4810886] Error: Error Domain=com.pixelglow.zipzap Code=0 "The operation couldn’t be completed. (com.pixelglow.zipzap error 0.)" UserInfo=0x174e60dc0 {NSUnderlyingError=0x174053560 "The operation couldn’t be completed. (Cocoa error 256.)"}
 09:14:59.341 [8549:4810886] File exists
 09:14:59.342 [8549:4810886] Crashed on RDG1_UpMain_29.00_to_28.00_17Feb2015.zip
 09:14:59.343 [8549:4810886] **********************************
 09:14:59.343 [8549:4810886] Error: Error Domain=com.pixelglow.zipzap Code=0 "The operation couldn’t be completed. (com.pixelglow.zipzap error 0.)" UserInfo=0x170a764c0 {NSUnderlyingError=0x17004d290 "The operation couldn’t be completed. (Cocoa error 256.)"}
 09:14:59.344 [8549:4810886] File exists
 09:14:59.344 [8549:4810886] Crashed on RDG1_UpMain_3.00_to_2.00_17Feb2015.zip
 09:14:59.346 [8549:4810886] **********************************
 09:14:59.346 [8549:4810886] Error: Error Domain=com.pixelglow.zipzap Code=0 "The operation couldn’t be completed. (com.pixelglow.zipzap error 0.)" UserInfo=0x170a76500 {NSUnderlyingError=0x17004d260 "The operation couldn’t be completed. (Cocoa error 256.)"}
 09:14:59.346 [8549:4810886] File exists
 09:14:59.346 [8549:4810886] Crashed on RDG1_UpMain_30.00_to_29.00_17Feb2015.zip
 09:14:59.348 [8549:4810886] **********************************
 09:14:59.348 [8549:4810886] Error: Error Domain=com.pixelglow.zipzap Code=0 "The operation couldn’t be completed. (com.pixelglow.zipzap error 0.)" UserInfo=0x170a765c0 {NSUnderlyingError=0x17004d1d0 "The operation couldn’t be completed. (Cocoa error 256.)"}
 09:14:59.349 [8549:4810886] File exists
 09:14:59.349 [8549:4810886] Crashed on RDG1_UpMain_31.00_to_30.00_17Feb2015.zip
 09:14:59.350 [8549:4810886] **********************************
 09:14:59.351 [8549:4810886] Error: Error Domain=com.pixelglow.zipzap Code=0 "The operation couldn’t be completed. (com.pixelglow.zipzap error 0.)" UserInfo=0x174e60f80 {NSUnderlyingError=0x174053620 "The operation couldn’t be completed. (Cocoa error 256.)"}
 09:14:59.351 [8549:4810886] File exists
 09:14:59.352 [8549:4810886] Crashed on RDG1_UpMain_32.00_to_31.00_17Feb2015.zip
 09:14:59.353 [8549:4810886] **********************************
 09:14:59.354 [8549:4810886] Error: Error Domain=com.pixelglow.zipzap Code=0 "The operation couldn’t be completed. (com.pixelglow.zipzap error 0.)" UserInfo=0x174c7fb00 {NSUnderlyingError=0x1740537a0 "The operation couldn’t be completed. (Cocoa error 256.)"}
 09:14:59.354 [8549:4810886] File exists
 09:14:59.354 [8549:4810886] Crashed on RDG1_UpMain_33.00_to_32.00_17Feb2015.zip
 09:14:59.356 [8549:4810886] **********************************
 09:14:59.356 [8549:4810886] Error: Error Domain=com.pixelglow.zipzap Code=0 "The operation couldn’t be completed. (com.pixelglow.zipzap error 0.)" UserInfo=0x170a76540 {NSUnderlyingError=0x17004d170 "The operation couldn’t be completed. (Cocoa error 256.)"}
 09:14:59.357 [8549:4810886] File exists
 09:14:59.357 [8549:4810886] Crashed on RDG1_UpMain_34.00_to_33.00_17Feb2015.zip
 09:14:59.358 [8549:4810886] **********************************
 09:14:59.359 [8549:4810886] Error: Error Domain=com.pixelglow.zipzap Code=0 "The operation couldn’t be completed. (com.pixelglow.zipzap error 0.)" UserInfo=0x170a76580 {NSUnderlyingError=0x17004d0e0 "The operation couldn’t be completed. (Cocoa error 256.)"}
 09:14:59.359 [8549:4810886] File exists
 09:14:59.359 [8549:4810886] Crashed on RDG1_UpMain_35.00_to_34.00_17Feb2015.zip
 09:14:59.361 [8549:4810886] **********************************
 09:14:59.361 [8549:4810886] Error: Error Domain=com.pixelglow.zipzap Code=0 "The operation couldn’t be completed. (com.pixelglow.zipzap error 0.)" UserInfo=0x174c7f780 {NSUnderlyingError=0x174053800 "The operation couldn’t be completed. (Cocoa error 256.)"}
 09:14:59.362 [8549:4810886] File exists
 09:14:59.362 [8549:4810886] Crashed on RDG1_UpMain_36.00_to_35.00_17Feb2015.zip
 09:14:59.364 [8549:4810886] **********************************
 09:14:59.364 [8549:4810886] File exists
 09:14:59.364 [8549:4810886] routeInfo.json
 09:14:59.365 [8549:4810886] Route0/Route0.xml
 09:14:59.365 [8549:4810886] Route0/Route0.pmd
 09:14:59.365 [8549:4810886] Working RDG1_UpMain_36.33_to_36.00_17Feb2015.zip
 09:14:59.365 [8549:4810886] **********************************
 09:14:59.367 [8549:4810886] **********************************
 09:14:59.367 [8549:4810886] Error: Error Domain=com.pixelglow.zipzap Code=0 "The operation couldn’t be completed. (com.pixelglow.zipzap error 0.)" UserInfo=0x174e61700 {NSUnderlyingError=0x174053ad0 "The operation couldn’t be completed. (Cocoa error 256.)"}
 09:14:59.368 [8549:4810886] File exists
 09:14:59.368 [8549:4810886] Crashed on RDG1_UpMain_4.00_to_3.00_17Feb2015.zip
 09:14:59.369 [8549:4810886] **********************************
 09:14:59.370 [8549:4810886] Error: Error Domain=com.pixelglow.zipzap Code=0 "The operation couldn’t be completed. (com.pixelglow.zipzap error 0.)" UserInfo=0x170a75fc0 {NSUnderlyingError=0x17004cba0 "The operation couldn’t be completed. (Cocoa error 256.)"}
 09:14:59.370 [8549:4810886] File exists
 09:14:59.370 [8549:4810886] Crashed on RDG1_UpMain_5.00_to_4.00_17Feb2015.zip
 09:14:59.372 [8549:4810886] **********************************
 09:14:59.372 [8549:4810886] Error: Error Domain=com.pixelglow.zipzap Code=0 "The operation couldn’t be completed. (com.pixelglow.zipzap error 0.)" UserInfo=0x174e61780 {NSUnderlyingError=0x174053bf0 "The operation couldn’t be completed. (Cocoa error 256.)"}
 09:14:59.373 [8549:4810886] File exists
 09:14:59.373 [8549:4810886] Crashed on RDG1_UpMain_6.00_to_5.00_17Feb2015.zip
 09:14:59.375 [8549:4810886] **********************************
 09:14:59.375 [8549:4810886] Error: Error Domain=com.pixelglow.zipzap Code=0 "The operation couldn’t be completed. (com.pixelglow.zipzap error 0.)" UserInfo=0x174e61800 {NSUnderlyingError=0x174053d70 "The operation couldn’t be completed. (Cocoa error 256.)"}
 09:14:59.375 [8549:4810886] File exists
 09:14:59.376 [8549:4810886] Crashed on RDG1_UpMain_7.00_to_6.00_17Feb2015.zip
 09:14:59.377 [8549:4810886] **********************************
 09:14:59.377 [8549:4810886] Error: Error Domain=com.pixelglow.zipzap Code=0 "The operation couldn’t be completed. (com.pixelglow.zipzap error 0.)" UserInfo=0x170a77580 {NSUnderlyingError=0x17004c660 "The operation couldn’t be completed. (Cocoa error 256.)"}
 09:14:59.378 [8549:4810886] File exists
 09:14:59.378 [8549:4810886] Crashed on RDG1_UpMain_8.00_to_7.00_17Feb2015.zip
 09:14:59.379 [8549:4810886] **********************************
 09:14:59.380 [8549:4810886] Error: Error Domain=com.pixelglow.zipzap Code=0 "The operation couldn’t be completed. (com.pixelglow.zipzap error 0.)" UserInfo=0x170a77800 {NSUnderlyingError=0x170051a00 "The operation couldn’t be completed. (Cocoa error 256.)"}
 09:14:59.380 [8549:4810886] File exists
 09:14:59.380 [8549:4810886] Crashed on RDG1_UpMain_9.00_to_8.00_17Feb2015.zip

Sorry for the long output but think it's all necessary. It's weird because it comes back working for a little while after it doesn't work, then stops working again.

**Comment by pixelglow** [comment] 2015-08-11 08:48
Weird bug indeed.

I'd suspect you're running out of memory and the autorelease pool is getting flooded. What device are you running this on?

You can try some of these tips:
* Try running it under or Instruments memory tool or observe the memory usage in Xcode.
* Step through `-[ZZArchive archiveWithURL:error:]`. It seems to be returning a `ZZOpenReadErrorCode` code.
* Put the inner loop in a `@autoreleasepool` scope.

If that doesn't work, you can send me a minimal project (DropBox etc.) that demos the bug, and I'll investigate further.

**Comment by benkofk** [comment] 2015-08-11 09:03
Hey, thanks for the fast reply. 

The autoreleasepool in the loop fixed it :+1: 

Thanks again,
Ben

**Comment by pixelglow** [comment] 2015-08-12 02:27
Cool, glad `@autoreleasepool` fixed it.

I'm curious and always want to improve the memory management, so a couple of trials if your code is still extant and you have the time/inclination:

* If you narrow the scope of the autorelease pool to surround just the declaration + use of `fileInfoInJSON` i.e. exclude the `ZZArchive` declaration, do you still get the same bug?
* If you delete the entire `fileInfoInJSON` code i.e. just leaving opening of `ZZArchive`, do you still get the same bug?
* If you keep the code as-is but build in release mode, do you still get the same bug?

I'm trying to isolate which item is flooding the autorelease pool, whether it was the archive opening or the data access.

**Comment by benkofk** [comment] 2015-08-12 07:44
> If you narrow the scope of the autorelease pool to surround just the declaration + use of fileInfoInJSON i.e. exclude the ZZArchive declaration, do you still get the same bug?

When I excluded ZZArchive and wrapped the fileInfoInJSON it flooded it again. 

> If you delete the entire fileInfoInJSON code i.e. just leaving opening of ZZArchive, do you still get the same bug?

Yes, all I have in the loop as i'm trying for you is: 

    NSString* zipfile = [[_documentsPath stringByAppendingPathComponent:section.sectionName] stringByAppendingPathComponent:child.fileName]; 
            NSError *error;
            ZZArchive* archive;
            archive = [ZZArchive archiveWithURL:[NSURL fileURLWithPath:zipfile]error:&error];
            NSLog(@"%@", archive);

and it's output is similar the same as my first output that I pasted (works for a few, lots of nulls, works for one, nulls)

> Build in release mode. In release mode, ARC is more aggressive about not putting things in the autorelease pool.

Removed the auto release pool & built in release mode and the error happens again

Hope this helps
Ben

**Comment by pixelglow** [comment] 2015-08-18 05:31
One more for the road:

If you replace the `+[ZZArchive archiveWithURL:error:]` call with `alloc` and `initWithURL:options:error:` call, and no autorelease pool, do you still get the error?

**Comment by pixelglow** [comment] 2015-08-27 14:02
OK, I'm closing this since the issue is resolved and no follow-up response.

**Closed by pixelglow** 2015-08-27 14:02 UTC

**Comment by benkofk** [comment] 2015-08-27 14:43
Hi Glen,

Sorry, I didn't see this email! I've finished at that company so I can't do it.

Cheers
